### ISSUE TITLE
enty-docs gatsby bug

### ISSUE THREAD

**Issue by dxinteractive** [blueflag/enty#62]
Not sure where to put this but will need to remember it if we use enty's proto gatsby docs thing in other places. Not really an enty bug per se.

So gatsby infers your schemas from the data, which works only if the data is complete at the time that it does the inferring. So playing around with a copy of enty-docs, if I were to remove all doclets that create `example`s, then gatsby would see there are no examples, not add the `example` field to the schema, and then any queries that talk about the `example` field would then break. Quite a problem, apparently they're working on it.

Issue: https://github.com/gatsbyjs/gatsby/issues/3344
Scheduled feature: https://github.com/gatsbyjs/gatsby/issues/4261

**Comment by allanhortle** [comment]
Yeah its pretty silly. The query at the bottom of the docs template constantly breaks because the docs you are querying have changed their data and now the inferred graphql types are different.

**Comment by allanhortle** [comment]
Closing as not really a problem with enty per say.
