### ISSUE TITLE
New enty RequestHock idea: `auto` config to be able to respond to props?

### ISSUE THREAD

**Issue by dxinteractive** [blueflag/enty#64]
We've had a use case where we want a hock to be able to operate as a QueryHock sometimes, and as a MutationHock at others. For example, if `props.coolId` exists, then make a request on mount, but if it doesn't then wait for `onMutate()` to be called later with the id. I figure this switching could happen if `auto` were a function that receives props, and return a boolean. If it returns `true` on mount, or has a prop changes of `false` -> `true`, then it could fire the request. Thoughts?

Other bad thoughts:
- Using a query hock and a matching nutation hock:
  - That means that those hock's props would need to be merged which is fiddly.
  - Using a query hock it always fires on mount, and depending on props you might not want it to fire. To prevent firing, given that you can't cancel a request using the `payloadCreator`, you'd have to have logic in the promise-returning function in the API to instruct a request to be cancelled, and while that's possible I think that's too far down the line.
- It's possible to place something *under* a single mutation hock that simply calls `onMutate()` under the right circumstances depending on props, and does nothing else.

**Comment by allanhortle** [comment]
Solved by the hooks release.
