### ISSUE TITLE
PropChangeHock to accept multiple types or args for controlling when to dispatch

### ISSUE THREAD

**Issue by dxinteractive** [blueflag/enty#8]
The 2nd arg currently accepts an array, specifying which params to listen to with `PropChangeListener`. It could do this:
- accept nothing (any falsey value) if you want to query only when the query string changes
- accepts an array if you want to listen to specific prop changes and fire dispatch on those
- accepts a `function(props: Object, nextProps: Object): Boolean` if you want to specify when to fire dispatch yourself.

Also consider how to trigger a query if no props have changed.

**Comment by dancoates** [comment]
Do you think we should account for combinations of the above approaches? 

eg. query when the query string changes OR when one of the props in the provided array changes?

**Comment by allanhortle** [comment]
Just plain old
